### ISSUE TITLE
Installation instructions not enough for a `@storybook/html` setup.

### ISSUE THREAD

**Issue by ringods** [renatomoor/storybook-tailwind-foundations#12]
Hello,

I added `storybook-tailwind-foundations` to my setup, which uses `@storybook/html`, according the installation instructions. But it doesn't seem to be enough. When running `npm run storybook`, I see errors like this:

```
ModuleParseError: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <script setup>
| import ColorsGrid from "./ColorsGrid.vue";
| 
    at handleParseError (/Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/webpack/lib/NormalModule.js:976:19)
    at /Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/webpack/lib/NormalModule.js:1095:5
    at processResult (/Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/webpack/lib/NormalModule.js:800:11)
    at /Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/webpack/lib/NormalModule.js:860:5
    at /Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (/Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at /Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/loader-runner/lib/LoaderRunner.js:224:4
    at /Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/webpack/lib/NormalModule.js:834:15
    at Array.eval (eval at create (/Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/ringods/Projects/personal/antora-ui-site-rds/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

Given your stories are implemented with Vue, I think I'm still missing part of the Vue related config. Can you update the README.md file with the extra config required to get this working?

**Comment by joediton** [comment]
I'm trying the exact same thing and getting the same results.
